GROUP_REPOS = [
        {
            "name": "DenDanskeMetode",
            "gitLinks": ["https://github.com/DenDanskeMetode/legacyProject"],
            "backend": "http:20.251.36.80/api",
            "frontend": "http://20.251.36.80",
            "monitoring": "http://20.251.36.80/grafana",
            "stack": ["Go", "PostgreSQL", "GHCR", "Azure", "GH workflows", "nginx", "Grafana", "Prometheus", "Docker"],
            "documentation": ["http://20.251.36.80/swagger","https://github.com/DenDanskeMetode/legacyProject/blob/master/readme.md"],
            "members": ["Felix Llambias", "Nicholas Ladik", "Christian Skovgaard", "Victor Lotz"],
        },
        {
            "name": "TheRizzlers",
            "gitLinks": ["https://github.com/TheRizzlersOrg4Semester/Rizzlerpies.git"],
            "backend": "https://20.251.147.233/apidocs/",
            "frontend": "https://20.251.147.233",
            "monitoring": "http://20.251.147.233:8080/dashboard/019dd42a-6f2e-7630-bb68-beb6ed248aed?relativeTime=1w",
            "stack": ["Node", "Express", "SSR (EJS)"],
            "documentation": ["https://github.com/TheRizzlersOrg4Semester/Rizzlerpies/tree/main/docs", "https://github.com/TheRizzlersOrg4Semester/Rizzlerpies/blob/main/README.md"],
            "members": ["Mike", "Johan", "Esben", "Mathias"],
        },
        {
            "name": "LNS",
            "gitLinks": ["https://github.com/Linus-nisse-segmentering/Agile-Linus"],
            "backend": "",
            "frontend": "",
            "monitoring": "",
            "stack": ["ruby","sinatra","rack/rackup", "puma", "ERB", "SQlite3", "HTML", "CSS"],
            "documentation": [],
            "members": ["Lukas", "Nixhajete", "Sahra"],
        },
        {
            "name": "Ostemadprissse",
            "gitLinks": ["https://github.com/ostemadprinsesse/Dinner-served-and-ate"],
            "backend": "https://github.com/ostemadprinsesse/Dinner-served-and-ate/pkgs/container/dinner-served-backend",
            "frontend": "https://github.com/ostemadprinsesse/Dinner-served-and-ate/pkgs/container/dinner-served-frontend",
            "monitoring": "",
            "stack": ["JavaScript, React, Node.js"],
            "documentation": ["https://github.com/ostemadprinsesse/Dinner-served-and-ate/blob/main/README.md"],
            "members": ["Linea", "Jonas", "Føen (Faprao)", "Nikoleta"],
        },
                {
            "name": "BalladeBaderne",
            "gitLinks": ["https://github.com/Balladebaderne/cookbook"],
            "backend": "http://172.189.59.40/api",
            "frontend": "http://172.189.59.40",
            "monitoring": "",
            "stack": ["Node.js", "Express", "React", "SQLite", "Docker", "Nginx", "Azure VM"],
            "documentation": ["http://172.189.59.40/apidocs/"],
            "members": ["Magnus Giemsa", "Laurits Munk", "Elias Garcia", "Andreas Brandenborg", "Jacob Bisgaard"],
        },
        {
            "name": "Andreas INC.",
            "gitLinks": ["https://github.com/AndreasRG/Awesome-Recipe-Book--2026-AndreasRG-Edition"],
            "backend": "http://131.163.81.147:5000/api/",
            "frontend": "http://131.163.81.147:5000/",
            "monitoring": "",
            "stack": ["Python", "SQLAlchemy", "FastAPI"],
            "documentation": ["http://131.163.81.147:5000/docs"],
            "members": ["Andreas Révész Gudmann"],
        }
]
